import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { Printer } from 'lucide-react';
import Loading from '../../components/Loading';
import ErrorMessage from '../../components/ErrorMessage';
import Button from '../../components/ui/Button';
import logoHeader from '../../assets/brand/logo-header.png';
import { getOrder } from '../../api/orders';
import { formatMoney, formatDate } from '../../utils/format';
import { extractErrorMessage } from '../../utils/errors';
import useDocumentTitle from '../../hooks/useDocumentTitle';

/**
 * Printable invoice — "Download PDF" is the browser's own print dialog
 * (Save as PDF), so no PDF-generation dependency is needed. See
 * src/styles/print.css for the `.no-print` rules that hide everything but
 * the invoice sheet when actually printing.
 */
export default function AccountOrderInvoice() {
  const { id } = useParams();
  const [order, setOrder] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    getOrder(id)
      .then(setOrder)
      .catch((err) => setError(extractErrorMessage(err)))
      .finally(() => setLoading(false));
  }, [id]);

  useDocumentTitle(order ? `Invoice #${order.id.slice(0, 8)}` : 'Invoice');

  if (loading) return <Loading />;
  if (error) return <ErrorMessage message={error} />;
  if (!order) return null;

  return (
    <div className="mx-auto max-w-3xl px-4 py-8">
      <div className="no-print mb-6 flex justify-end">
        <Button onClick={() => window.print()}>
          <Printer className="h-4 w-4" />
          Print / Save as PDF
        </Button>
      </div>

      <div className="invoice-sheet rounded-2xl border border-slate-200 bg-white p-10 text-slate-900 shadow-soft dark:border-slate-800 dark:bg-slate-900 dark:text-white">
        <div className="mb-8 flex items-start justify-between">
          <img src={logoHeader} alt="G&D Commerce" className="h-10 object-contain" />
          <div className="text-right">
            <h1 className="text-h3 font-semibold">Invoice</h1>
            <p className="text-small text-slate-500 dark:text-slate-400">#{order.id.slice(0, 8)}</p>
          </div>
        </div>

        <div className="mb-8 grid grid-cols-2 gap-6 text-small">
          <div>
            <p className="mb-1 font-semibold text-slate-500 dark:text-slate-400">Order Date</p>
            <p>{formatDate(order.createdAt)}</p>
          </div>
          <div className="text-right">
            <p className="mb-1 font-semibold text-slate-500 dark:text-slate-400">Status</p>
            <p>{order.status}</p>
          </div>
          {order.shippingAddress && (
            <div className="col-span-2">
              <p className="mb-1 font-semibold text-slate-500 dark:text-slate-400">Shipping Address</p>
              <p>
                {order.shippingAddress.line1}
                {order.shippingAddress.line2 ? `, ${order.shippingAddress.line2}` : ''}, {order.shippingAddress.city},{' '}
                {order.shippingAddress.state} {order.shippingAddress.postalCode}, {order.shippingAddress.country}
              </p>
            </div>
          )}
        </div>

        <table className="mb-8 w-full text-small">
          <thead>
            <tr className="border-b border-slate-300 text-left text-caption uppercase tracking-wide text-slate-500 dark:border-slate-700 dark:text-slate-400">
              <th className="py-2">Item</th>
              <th className="py-2 text-right">Unit Price</th>
              <th className="py-2 text-right">Qty</th>
              <th className="py-2 text-right">Amount</th>
            </tr>
          </thead>
          <tbody>
            {order.items.map((item) => (
              <tr key={item.id} className="border-b border-slate-100 dark:border-slate-800">
                <td className="py-2">{item.productName}</td>
                <td className="py-2 text-right">{formatMoney(item.unitPriceCents)}</td>
                <td className="py-2 text-right">{item.quantity}</td>
                <td className="py-2 text-right">{formatMoney(item.unitPriceCents * item.quantity)}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <div className="flex justify-end">
          <div className="w-48">
            <div className="flex justify-between border-t border-slate-300 pt-2 text-h4 font-semibold dark:border-slate-700">
              <span>Total</span>
              <span>{formatMoney(order.totalCents, order.currency)}</span>
            </div>
          </div>
        </div>

        <p className="mt-10 text-center text-caption text-slate-400 dark:text-slate-500">
          Demo application — no real payments. Generated by G&amp;D Commerce.
        </p>
      </div>
    </div>
  );
}
